# LOCALHOST

### Get all friends
GET http://localhost:3000/friends


### Get contact by id
GET http://localhost:3000/friends/65b6703f7a00466ca34fe1a0


### Create friends
POST http://localhost:3000/friends HTTP/1.1
content-type: application/json

{
    "name": "John Doe",
    "surname": "mugijima",
    "phone":"+48 567 923 123",
    "email": "test4@test.com",
    "username": "test4@test.com",
    "color": "black",
    "city": "mutare",
    "ipaddress": "94.121.168.53"
}

### Update user
PUT http://localhost:3000/friends/65b6703f7a00466ca34fe1a0 HTTP/1.1
content-type: application/json

{
    "name": "John Doe",
    "surname": "mutero",
    "phone":"+263 78 6414 606",
    "email": "test4@test.com",
    "username": "test4@test.com",
    "color": "black",
    "city": "mutare",
    "ipaddress": "94.121.168.53"
}


### Delete user
DELETE http://localhost:3000/friends/65b66fe4c1b2e3562d50e8ea